@echo off
setlocal enabledelayedexpansion

set PYTHON=venv\Scripts\python
set APP_NAME=ApexDatabase
set APP_DISPLAY_NAME=Apex Database
set APP_AUTHOR=Rock Solid Data
set "APP_DESCRIPTION=Catalog, Inventory & Invoicing"

:: Read version from VERSION file
for /f "usebackq delims=" %%v in (`type VERSION`) do set APP_VERSION=%%v
if "%APP_VERSION%"=="" (
    echo [ERROR] Could not read VERSION file
    exit /b 1
)

echo.
echo ============================================
echo   %APP_NAME% v%APP_VERSION% - Build (Inno Setup)
echo ============================================
echo.

set "BUILD_MODE=%~1"
if "%BUILD_MODE%"=="" set "BUILD_MODE=all"
set "BUILD_DIR=build\%APP_NAME%"

if /i "%BUILD_MODE%"=="clean" goto :clean
if /i "%BUILD_MODE%"=="freeze" goto :freeze
if /i "%BUILD_MODE%"=="inno" goto :inno
if /i "%BUILD_MODE%"=="test" goto :test
if /i "%BUILD_MODE%"=="all" goto :all
if /i "%BUILD_MODE%"=="help" goto :help
echo Unknown action: %BUILD_MODE%
goto :help

:help
echo Usage: build_installer.bat [action]
echo   (none) - Full build    freeze - Exe only
echo   inno   - Installer     test   - Run debug
echo   clean  - Remove build  help   - This message
exit /b 0

:clean
echo [CLEAN] Removing build artifacts...
if exist build rmdir /s /q build 2>nul
if exist dist rmdir /s /q dist 2>nul
if exist staticfiles rmdir /s /q staticfiles 2>nul
if exist Output rmdir /s /q Output 2>nul
if exist seed.sqlite3 del /q seed.sqlite3 2>nul
echo [CLEAN] Done.
exit /b 0

:check_prereqs
%PYTHON% --version >nul 2>&1 || (echo [ERROR] Python not found! & exit /b 1)
%PYTHON% -c "import cx_Freeze" >nul 2>&1 || %PYTHON% -m pip install cx_Freeze
%PYTHON% -c "import waitress" >nul 2>&1 || %PYTHON% -m pip install waitress
%PYTHON% -c "import whitenoise" >nul 2>&1 || %PYTHON% -m pip install whitenoise
exit /b 0

:freeze
call :check_prereqs
if errorlevel 1 exit /b 1
echo [1/3] Exporting seed data...
%PYTHON% manage.py export_seed_data
if errorlevel 1 (echo [WARNING] Seed export failed -- building without seed data)
echo [2/3] Collecting static files...
%PYTHON% manage.py collectstatic --noinput
echo [3/3] Freezing application...
if exist "%BUILD_DIR%" rmdir /s /q "%BUILD_DIR%" 2>nul
%PYTHON% setup_cx_freeze.py build
if errorlevel 1 (echo [ERROR] Build failed! & exit /b 1)
if not exist "%BUILD_DIR%\%APP_NAME%.exe" (echo [ERROR] Output not found! & exit /b 1)
echo [DONE] Frozen app: %BUILD_DIR%\
if "%BUILD_MODE%"=="freeze" exit /b 0
goto :eof

:inno
if not exist "%BUILD_DIR%\%APP_NAME%.exe" (echo [ERROR] Run freeze first & exit /b 1)

:: Read UPGRADE_CODE from .upgrade_code file (generated by freeze step)
set "UPGRADE_CODE="
if exist ".upgrade_code" (
    for /f "usebackq delims=" %%u in (`type .upgrade_code`) do set UPGRADE_CODE=%%u
)
if "!UPGRADE_CODE!"=="" (
    echo [ERROR] .upgrade_code not found -- run freeze first
    exit /b 1
)
:: Strip braces -- Inno Setup interprets { as a constant reference
set "UPGRADE_CODE=!UPGRADE_CODE:{=!"
set "UPGRADE_CODE=!UPGRADE_CODE:}=!"

:: Find Inno Setup compiler
set "ISCC="
if exist "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" set "ISCC=C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
if exist "C:\Program Files\Inno Setup 6\ISCC.exe" set "ISCC=C:\Program Files\Inno Setup 6\ISCC.exe"
if "!ISCC!"=="" (where iscc >nul 2>&1 && for /f "delims=" %%p in ('where iscc') do set "ISCC=%%p")
if "!ISCC!"=="" (echo [ERROR] Inno Setup 6 not found! Download: https://jrsoftware.org/isinfo.php & exit /b 1)

if not exist dist mkdir dist

:: Quote defines that contain spaces to avoid ISCC argument splitting
set "DEFINES=/DAppName=%APP_NAME%"
set "DEFINES=%DEFINES% "/DAppDisplayName=%APP_DISPLAY_NAME%""
set "DEFINES=%DEFINES% /DAppVersion=%APP_VERSION%"
set "DEFINES=%DEFINES% "/DAppAuthor=%APP_AUTHOR%""
set "DEFINES=%DEFINES% "/DAppDescription=%APP_DESCRIPTION%""
set "DEFINES=%DEFINES% /DUpgradeCode=!UPGRADE_CODE!"
set "DEFINES=%DEFINES% /DBuildDir=%BUILD_DIR%"
if exist "app.ico" set "DEFINES=%DEFINES% /DIconFile=app.ico"

"!ISCC!" %DEFINES% installer.iss
if errorlevel 1 (echo [ERROR] Inno build failed! & exit /b 1)
echo [DONE] Installer: dist\%APP_NAME%_Setup_v%APP_VERSION%.exe
exit /b 0

:test
if not exist "%BUILD_DIR%\%APP_NAME%_Debug.exe" (echo [ERROR] Run freeze first & exit /b 1)
start "" "%BUILD_DIR%\%APP_NAME%_Debug.exe"
exit /b 0

:all
call :freeze
if errorlevel 1 exit /b 1
call :inno
if errorlevel 1 exit /b 1
echo.
echo BUILD SUCCESSFUL! Installer in dist\
exit /b 0
