from django.urls import path

from . import views

app_name = "catalog"

urlpatterns = [
    path("", views.home, name="home"),
    path("image-viewer/", views.image_viewer, name="image_viewer"),
    path("applications/", views.application_list, name="application_list"),
    path("applications/add/", views.application_create, name="application_create"),
    path("applications/<int:pk>/", views.application_detail, name="application_detail"),
    path("applications/<int:pk>/edit/", views.application_edit, name="application_edit"),
    path("applications/<int:pk>/delete/", views.application_delete, name="application_delete"),
    path("applications/<int:pk>/link-unit/", views.application_link_unit, name="application_link_unit"),
    path("applications/<int:pk>/unlink-unit/<int:unit_pk>/", views.application_unlink_unit, name="application_unlink_unit"),
    path("applications/<int:pk>/spec/add/", views.application_spec_add, name="application_spec_add"),
    path("applications/<int:pk>/spec/<int:spec_pk>/edit/", views.application_spec_edit, name="application_spec_edit"),
    path("applications/<int:pk>/spec/<int:spec_pk>/delete/", views.application_spec_delete, name="application_spec_delete"),
    path("applications/types/", views.application_type_list, name="application_type_list"),
    path("applications/types/add/", views.application_type_create, name="application_type_create"),
    path("applications/types/<int:pk>/", views.application_type_detail, name="application_type_detail"),
    path("applications/types/<int:pk>/edit/", views.application_type_edit, name="application_type_edit"),
    path("applications/types/<int:pk>/delete/", views.application_type_delete, name="application_type_delete"),
    path("applications/type-fields/<str:type_name>/", views.application_type_fields_api, name="application_type_fields_api"),
    path("api/application-custom-field/add/", views.application_custom_field_add_api, name="application_custom_field_add_api"),
    path("bom/", views.bom_list, name="bom_list"),
    path("bom/add/", views.bom_create, name="bom_create"),
    path("bom/<int:pk>/", views.bom_detail, name="bom_detail"),
    path("bom/<int:pk>/print/", views.bom_print, name="bom_print"),
    path("bom/<int:pk>/add-part/", views.bom_item_add, name="bom_item_add"),
    path("bom/<int:pk>/item/<int:item_pk>/", views.bom_item_detail, name="bom_item_detail"),
    path("bom/<int:pk>/item/<int:item_pk>/edit/", views.bom_item_edit, name="bom_item_edit"),
    path("bom/<int:pk>/item/<int:item_pk>/delete/", views.bom_item_delete, name="bom_item_delete"),
    path("bom/<int:pk>/edit/", views.bom_edit, name="bom_edit"),
    path("bom/<int:pk>/delete/", views.bom_delete, name="bom_delete"),
    path("parts/", views.part_list, name="part_list"),
    path("parts/add/", views.part_create, name="part_create"),
    path("parts/categories/", views.part_category_list, name="part_category_list"),
    path("parts/categories/add/", views.part_category_create, name="part_category_create"),
    path("parts/categories/<int:pk>/", views.part_category_detail, name="part_category_detail"),
    path("parts/categories/<int:pk>/edit/", views.part_category_edit, name="part_category_edit"),
    path("parts/categories/<int:pk>/delete/", views.part_category_delete, name="part_category_delete"),
    path("parts/category-fields/<str:category>/", views.part_category_fields_api, name="part_category_fields_api"),
    path("api/part-category-custom-field/add/", views.part_category_custom_field_add_api, name="part_category_custom_field_add_api"),
    path("parts/upload-csv/", views.part_upload_csv, name="part_upload_csv"),
    path("parts/csv-template/", views.part_download_csv_template, name="part_download_csv_template"),
    path("parts/<int:pk>/", views.part_detail, name="part_detail"),
    path("parts/<int:pk>/edit/", views.part_edit, name="part_edit"),
    path("parts/<int:pk>/delete/", views.part_delete, name="part_delete"),
    path("parts/<int:pk>/substitute/add/", views.part_substitute_add, name="part_substitute_add"),
    path("parts/<int:pk>/substitute/<int:sub_pk>/delete/", views.part_substitute_delete, name="part_substitute_delete"),
    path("parts/<int:pk>/interchange/add/", views.part_interchange_add, name="part_interchange_add"),
    path("parts/<int:pk>/interchange/<int:int_pk>/edit/", views.part_interchange_edit, name="part_interchange_edit"),
    path("parts/<int:pk>/interchange/<int:int_pk>/delete/", views.part_interchange_delete, name="part_interchange_delete"),
    path("parts/<int:pk>/superseding/add/", views.part_superseding_add, name="part_superseding_add"),
    path("parts/<int:pk>/superseding/<int:sup_pk>/delete/", views.part_superseding_delete, name="part_superseding_delete"),
    path("units/", views.unit_list, name="unit_list"),
    path("units/search/", views.unit_search, name="unit_search"),
    path("units/add/", views.unit_create, name="unit_create"),
    path("units/type-categories/", views.unit_type_category_list, name="unit_type_category_list"),
    path("units/type-categories/add/", views.unit_type_category_create, name="unit_type_category_create"),
    path("units/type-categories/<int:pk>/", views.unit_type_category_detail, name="unit_type_category_detail"),
    path("units/type-categories/<int:pk>/edit/", views.unit_type_category_edit, name="unit_type_category_edit"),
    path("units/type-categories/<int:pk>/delete/", views.unit_type_category_delete, name="unit_type_category_delete"),
    path("units/type-category-fields/<str:type_name>/", views.unit_type_category_fields_api, name="unit_type_category_fields_api"),
    path("api/unit-type-custom-field/add/", views.unit_type_custom_field_add_api, name="unit_type_custom_field_add_api"),
    path("units/upload-csv/", views.unit_upload_csv, name="unit_upload_csv"),
    path("units/csv-template/", views.unit_download_csv_template, name="unit_download_csv_template"),
    path("units/<int:pk>/", views.unit_detail, name="unit_detail"),
    path("units/<int:pk>/edit/", views.unit_edit, name="unit_edit"),
    path("units/<int:pk>/delete/", views.unit_delete, name="unit_delete"),
    path("units/<int:pk>/bom/", views.unit_bom_view, name="unit_bom"),
    path("units/<int:pk>/cross-ref/add/", views.cross_reference_add, name="cross_reference_add"),
    path("units/<int:pk>/cross-ref/<int:cr_pk>/", views.cross_reference_detail, name="cross_reference_detail"),
    path("units/<int:pk>/cross-ref/<int:cr_pk>/edit/", views.cross_reference_edit, name="cross_reference_edit"),
    path("units/<int:pk>/cross-ref/<int:cr_pk>/delete/", views.cross_reference_delete, name="cross_reference_delete"),
    path("units/<int:pk>/substitute/add/", views.substitute_add, name="substitute_add"),
    path("units/<int:pk>/substitute/<int:sub_pk>/delete/", views.substitute_delete, name="substitute_delete"),
    path("units/<int:pk>/gear-reduction/add/", views.gear_reduction_add, name="gear_reduction_add"),
    path("units/<int:pk>/gear-reduction/<int:gr_pk>/edit/", views.gear_reduction_edit, name="gear_reduction_edit"),
    path("units/<int:pk>/gear-reduction/<int:gr_pk>/delete/", views.gear_reduction_delete, name="gear_reduction_delete"),

    # BOM AJAX API endpoints (modal-based add-part flow)
    path("api/bom/save/", views.bom_save_api, name="bom_save_api"),
    path("api/bom/<int:pk>/add-part/", views.bom_item_add_api, name="bom_item_add_api"),
    path("api/bom/<int:pk>/item/<int:item_pk>/delete/", views.bom_item_delete_api, name="bom_item_delete_api"),

    # Autocomplete JSON endpoints (Tom Select AJAX)
    path("api/units/autocomplete/", views.unit_autocomplete, name="unit_autocomplete"),
    path("api/parts/autocomplete/", views.part_autocomplete, name="part_autocomplete"),
    path("api/parts/<int:pk>/detail/", views.part_detail_api, name="part_detail_api"),
    path("api/applications/autocomplete/", views.application_autocomplete, name="application_autocomplete"),
]
