# Generated by Django 6.0.1 on 2026-03-09 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='fax',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='remit_city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='remit_line1',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Address Line 1'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='remit_line2',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Address Line 2'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='remit_state',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='State / Province'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='remit_zip',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='ZIP / Postal Code'),
        ),
        migrations.CreateModel(
            name='VendorContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('fax', models.CharField(blank=True, default='', max_length=50)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='inventory.vendor')),
            ],
            options={
                'ordering': ['-is_primary', 'ordering', 'pk'],
            },
        ),
    ]
