# Generated by Django 6.0.2 on 2026-03-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_vendor_account_number_vendor_fax_vendor_remit_city_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['name'], name='inventory_v_name_f75e09_idx'),
        ),
    ]
