# Generated by Django 6.0.2 on 2026-02-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='private_notes',
            field=models.TextField(blank=True, default='', verbose_name='Private Notes (internal)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Invoice Notes (for customer)'),
        ),
    ]
