# Generated by Django 6.0.2 on 2026-02-11

from django.db import migrations, models
import django.db.models.deletion


def backfill_customer_fields(apps, schema_editor):
    Invoice = apps.get_model('invoicing', 'Invoice')
    for inv in Invoice.objects.select_related('customer').filter(customer__isnull=False):
        inv.customer_name = inv.customer.name or ''
        inv.contact_name = ''
        inv.phone = inv.customer.phone or ''
        inv.email = inv.customer.email or ''
        addr_parts = [inv.customer.address_line1, inv.customer.address_line2]
        if inv.customer.city or inv.customer.state or inv.customer.zip_code:
            addr_parts.append(f"{inv.customer.city or ''}, {inv.customer.state or ''} {inv.customer.zip_code or ''}".strip().strip(','))
        inv.address = '\n'.join(p for p in addr_parts if p)
        inv.save()


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_add_private_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Customer Name'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Contact Name'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoicing.customer'),
        ),
        migrations.RunPython(backfill_customer_fields, migrations.RunPython.noop),
    ]
