# Generated by Django 6.0.2 on 2026-02-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_invoice_customer_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Manchester Electric', max_length=255)),
                ('tagline', models.CharField(blank=True, default='Professional electrical solutions', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('default_net_terms', models.CharField(choices=[('NET_10', 'Net 10'), ('NET_30', 'Net 30'), ('DUE_ON_RECEIPT', 'Net due on receipt'), ('CUSTOM', 'Custom')], default='NET_30', max_length=20)),
                ('default_net_days', models.PositiveIntegerField(default=30, help_text='Days when default_net_terms is Custom')),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='net_days',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Custom days when net_terms is Custom'),
        ),
        migrations.AddField(
            model_name='customer',
            name='net_terms',
            field=models.CharField(blank=True, choices=[('NET_10', 'Net 10'), ('NET_30', 'Net 30'), ('DUE_ON_RECEIPT', 'Net due on receipt'), ('CUSTOM', 'Custom')], help_text='Override default payment terms. Leave blank to use company default.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
