# Generated by Django 6.0.2 on 2026-02-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_add_company_settings_and_net_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Used when creating new invoices. Customers can override on their profile.', max_digits=5, verbose_name='Default Tax Rate (%)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override default tax rate for this customer. Leave blank to use company default.', max_digits=5, null=True, verbose_name='Tax Rate (%)'),
        ),
    ]
