# Generated by Django 6.0.2 on 2026-02-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_add_default_tax_and_customer_tax_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='invoice_currency_symbol',
            field=models.CharField(default='$', max_length=10),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='invoice_date_format',
            field=models.CharField(choices=[('F j, Y', 'Month DD, YYYY'), ('m/d/Y', 'MM/DD/YYYY'), ('d/m/Y', 'DD/MM/YYYY')], default='F j, Y', max_length=20),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='invoice_layout_style',
            field=models.CharField(choices=[('standard', 'Standard'), ('compact', 'Compact')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='invoice_number_include_year',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='invoice_number_padding',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='invoice_number_prefix',
            field=models.CharField(default='INV-', max_length=20),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='invoice_paper_size',
            field=models.CharField(choices=[('letter', 'Letter'), ('a4', 'A4')], default='letter', max_length=10),
        ),
    ]
