# Generated by Django 6.0.2 on 2026-02-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_add_invoice_format_and_numbering'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='invoice_number_include_month',
            field=models.BooleanField(default=False, help_text='Include month in number (e.g. INV-202602-0001). Only applies when year is included.'),
        ),
    ]
