# Generated by Django 6.0.1 on 2026-03-09 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0007_add_invoice_number_include_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address_line1',
            new_name='bill_to_line1',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='address_line2',
            new_name='bill_to_line2',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='city',
            new_name='bill_to_city',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='state',
            new_name='bill_to_state',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='zip_code',
            new_name='bill_to_zip',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='fax',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='has_st105',
            field=models.BooleanField(default=False, verbose_name='ST105 on file'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_tax_exempt',
            field=models.BooleanField(default=False, verbose_name='Tax Exempt'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ship_to_city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ship_to_line1',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Address Line 1'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ship_to_line2',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Address Line 2'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ship_to_state',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='State / Province'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ship_to_zip',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='ZIP / Postal Code'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Discount %'),
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('fax', models.CharField(blank=True, default='', max_length=50)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='invoicing.customer')),
            ],
            options={
                'ordering': ['-is_primary', 'ordering', 'pk'],
            },
        ),
    ]
