# Generated by Django 6.0.1 on 2026-03-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0008_rename_address_line1_customer_bill_to_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bill_to_city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='City'),
        ),
    ]
