# Generated by Django 6.0.2 on 2026-04-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0010_customer_contact_name_customer_email_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='company_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
