# Generated by Django 6.0.1 on 2026-04-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0011_clear_company_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='pricing_method',
            field=models.CharField(choices=[('markup', 'Markup  (Sell = Cost ÷ Factor)'), ('margin', 'Margin  (Sell = Cost × (1 + Rate))')], default='markup', max_length=10, verbose_name='Resell Calculation Method'),
        ),
    ]
