# Generated by Django 6.0.1 on 2026-05-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0012_add_pricing_method_to_companysettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='pricing_method',
            field=models.CharField(choices=[('markup', 'Markup  (Sell = Cost ÷ Factor)'), ('margin', 'Margin  (Sell = Cost × (1 + %))')], default='markup', max_length=10, verbose_name='Resell Calculation Method'),
        ),
    ]
