# Generated by Django 6.0.1 on 2026-05-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0013_alter_companysettings_pricing_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='invoice_number_include_month',
            field=models.BooleanField(default=False, help_text='Include month in number (e.g. INV-2602-0001). Only applies when year is included.'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='invoice_number_prefix',
            field=models.CharField(blank=True, default='INV-', max_length=20),
        ),
    ]
