# Generated by Django 6.0.1 on 2026-05-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0014_alter_companysettings_invoice_number_include_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='invoice_footer_message',
            field=models.TextField(blank=True, default='', help_text='Appears at the bottom of every invoice (e.g. thank-you note, payment instructions).', verbose_name='Default Footer Message'),
        ),
    ]
