# Generated by Django 6.0.2 on 2026-02-10 19:59

from django.db import migrations


UNIT_TYPES = [
    ("AC Motor", "Alternating-current motor"),
    ("DC Motor", "Direct-current motor"),
    ("Generator", "Generator"),
    ("Starter", "Starter motor"),
    ("Alternator", "Alternator"),
    ("Pump", "Pump"),
]


def seed_unit_types(apps, schema_editor):
    UnitType = apps.get_model("catalog", "UnitType")
    for name, description in UNIT_TYPES:
        UnitType.objects.get_or_create(name=name, defaults={"description": description})


def remove_unit_types(apps, schema_editor):
    UnitType = apps.get_model("catalog", "UnitType")
    UnitType.objects.filter(name__in=[n for n, _ in UNIT_TYPES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_unit_types, remove_unit_types),
    ]
