# Generated by Django 6.0.2 on 2026-02-11 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_unit_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('type', models.CharField(blank=True, default='', max_length=100)),
                ('specification', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='catalog.application')),
            ],
            options={
                'verbose_name': 'Application Specification',
                'verbose_name_plural': 'Application Specifications',
                'ordering': ['category', 'type'],
            },
        ),
    ]
