# Generated by Django 6.0.2 on 2026-02-18 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_add_application_specification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='crossreference',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='application',
            name='alt_pulley',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Alt Pulley'),
        ),
        migrations.AddField(
            model_name='application',
            name='fuel_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Fuel Type'),
        ),
        migrations.AddField(
            model_name='application',
            name='unit_type_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Unit Type'),
        ),
        migrations.AddField(
            model_name='application',
            name='vin',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='VIN'),
        ),
        migrations.AddField(
            model_name='crossreference',
            name='cross_ref_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='crossreference',
            name='interchange_type',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Manufacturer / Source'),
        ),
        migrations.AddField(
            model_name='unit',
            name='clock_position',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Clock Position'),
        ),
        migrations.AddField(
            model_name='unit',
            name='pulley_class',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Pulley Class'),
        ),
        migrations.AddField(
            model_name='unit',
            name='starter_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Starter Type'),
        ),
        migrations.AlterField(
            model_name='crossreference',
            name='cross_ref_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cross_referenced_by', to='catalog.unit'),
        ),
        migrations.AlterUniqueTogether(
            name='crossreference',
            unique_together={('unit', 'cross_ref_number', 'interchange_type')},
        ),
        migrations.AddIndex(
            model_name='crossreference',
            index=models.Index(fields=['cross_ref_number'], name='catalog_cro_cross_r_ef0372_idx'),
        ),
        migrations.AddIndex(
            model_name='crossreference',
            index=models.Index(fields=['interchange_type'], name='catalog_cro_interch_217ea3_idx'),
        ),
    ]
