# Generated by Django 6.0.2 on 2026-02-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_crossreference_unique_together_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['year'], name='catalog_app_year_090e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['mfr'], name='catalog_app_mfr_95fe1b_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['volt'], name='catalog_app_volt_e8dcb9_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['is_active'], name='catalog_app_is_acti_7d8ed5_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['voltage'], name='catalog_uni_voltage_c27282_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['family'], name='catalog_uni_family_24e7c3_idx'),
        ),
    ]
