# Generated by Django 6.0.1 on 2026-03-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_application_catalog_app_year_090e6a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
