# Generated by Django 6.0.1 on 2026-03-10 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_add_part_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='linked_parts', to='catalog.unit'),
        ),
        migrations.CreateModel(
            name='PartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='parts/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.part')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
