# Generated by Django 6.0.1 on 2026-03-11 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_seed_part_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitTypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Unit Type Category',
                'verbose_name_plural': 'Unit Type Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_type_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='UnitTypeCategoryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_label', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='catalog.unittypecategory')),
            ],
            options={
                'ordering': ['display_order', 'pk'],
                'unique_together': {('category', 'field_name')},
            },
        ),
    ]
