# Generated by Django 6.0.1 on 2026-03-11 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_rename_key_to_manufacturer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='manufacturer_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Manufacturer Number'),
        ),
        migrations.CreateModel(
            name='PartSuperseding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_part_number', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('old_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='catalog.part')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supersedings', to='catalog.part')),
            ],
        ),
        migrations.CreateModel(
            name='PartInterchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interchange_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interchanged_by_parts', to='catalog.part')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_interchanges', to='catalog.part')),
            ],
            options={
                'unique_together': {('part', 'interchange_part')},
            },
        ),
        migrations.CreateModel(
            name='PartSubstitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_substitutes', to='catalog.part')),
                ('substitute_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituted_by_parts', to='catalog.part')),
            ],
            options={
                'unique_together': {('part', 'substitute_part')},
            },
        ),
    ]
