# Generated by Django 6.0.1 on 2026-03-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_add_default_fields_to_part_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='voltage',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Voltage'),
        ),
    ]
