# Generated by Django 6.0.1 on 2026-03-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_add_voltage_to_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
    ]
