# Generated by Django 6.0.1 on 2026-03-12 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_add_unit_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Application Type',
                'verbose_name_plural': 'Application Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationTypeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_label', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='catalog.applicationtype')),
            ],
            options={
                'ordering': ['display_order', 'pk'],
                'unique_together': {('application_type', 'field_name')},
            },
        ),
    ]
