# Generated by Django 6.0.1 on 2026-03-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_applicationtype_applicationtypefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_type_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='type_specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
