# Generated by Django 6.0.2 on 2026-03-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_application_application_type_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partsuperseding',
            unique_together={('part', 'old_part_number')},
        ),
        migrations.AddIndex(
            model_name='applicationspecification',
            index=models.Index(fields=['application', 'category'], name='catalog_app_applica_305855_idx'),
        ),
        migrations.AddIndex(
            model_name='bomitem',
            index=models.Index(fields=['bom', 'part'], name='catalog_bom_bom_id_623f0c_idx'),
        ),
    ]
