# Generated by Django 6.0.1 on 2026-03-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_add_indexes_and_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='model',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
