# Generated by Django 6.0.1 on 2026-03-16 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_add_model_to_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='partinterchange',
            name='interchange_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='partsubstitute',
            name='substitute_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='substitute',
            name='substitute_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='partinterchange',
            name='interchange_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interchanged_by_parts', to='catalog.part'),
        ),
        migrations.AlterField(
            model_name='partsubstitute',
            name='substitute_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituted_by_parts', to='catalog.part'),
        ),
        migrations.AlterField(
            model_name='substitute',
            name='substitute_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituted_by', to='catalog.unit'),
        ),
    ]
