# Generated by Django 6.0.1 on 2026-03-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_add_manual_number_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_number',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_number',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
    ]
