# Generated by Django 6.0.1 on 2026-03-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_allow_blank_unit_and_part_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_number',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
