# Generated by Django 6.0.1 on 2026-03-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_unit_number_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='kw',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='KW'),
        ),
    ]
