# Generated by Django 6.0.1 on 2026-04-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_populate_seed_id_from_pk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unittypecategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Unit Type Category', 'verbose_name_plural': 'Unit Type Categories'},
        ),
        migrations.AddField(
            model_name='unittypecategory',
            name='color',
            field=models.CharField(default='#fd7e14', max_length=7),
        ),
        migrations.AddField(
            model_name='unittypecategory',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
