# Generated by Django 6.0.1 on 2026-04-22 16:38

from django.db import migrations


CATEGORY_DEFAULTS = {
    "Alternator":  {"sort_order": 10, "color": "#4a6fa5"},
    "Starter":     {"sort_order": 20, "color": "#a3423a"},
    "Generator":   {"sort_order": 30, "color": "#3d7d78"},
    "Mild Hybrid (MGU)": {"sort_order": 40, "color": "#6b5b95"},
    "AC Motor":    {"sort_order": 50, "color": "#b38234"},
    "DC Motor":    {"sort_order": 60, "color": "#4e5d8e"},
    "Pump":        {"sort_order": 70, "color": "#8b6d7e"},
}


def set_order_and_colors(apps, schema_editor):
    UnitTypeCategory = apps.get_model("catalog", "UnitTypeCategory")
    for cat in UnitTypeCategory.objects.all():
        defaults = CATEGORY_DEFAULTS.get(cat.name)
        if defaults:
            cat.sort_order = defaults["sort_order"]
            cat.color = defaults["color"]
            cat.save(update_fields=["sort_order", "color"])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_add_sort_order_and_color_to_unittypecategory'),
    ]

    operations = [
        migrations.RunPython(set_order_and_colors, migrations.RunPython.noop),
    ]
