# Generated by Django 6.0.1 on 2026-04-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_clean_application_unit_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='track_inventory',
            field=models.BooleanField(default=False, verbose_name='Track Inventory'),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='unit_qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Part Qty'),
        ),
    ]
