# Generated by Django 6.0.1 on 2026-04-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_add_track_inventory_to_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='markup_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Markup %'),
        ),
    ]
