# Generated by Django 6.0.1 on 2026-05-05 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_seed_default_fields_to_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='markup_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Markup'),
        ),
        migrations.AlterField(
            model_name='part',
            name='primary_vendor',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Primary Supplier'),
        ),
        migrations.CreateModel(
            name='UnitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='units/')),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.unit')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
