# Generated by Django 6.0.1 on 2026-05-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_unit_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crossreference',
            options={'ordering': ['interchange_type', 'cross_ref_number'], 'verbose_name': 'Cross Reference', 'verbose_name_plural': 'Cross References'},
        ),
    ]
