# Generated by Django 6.0.1 on 2026-05-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_alter_crossreference_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['unit_number'], name='catalog_app_unit_nu_2b4af2_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['model'], name='catalog_app_model_b93c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['part_number'], name='catalog_app_part_nu_99ef2b_idx'),
        ),
        migrations.AddIndex(
            model_name='bomitem',
            index=models.Index(fields=['oem_number'], name='catalog_bom_oem_num_b4071c_idx'),
        ),
        migrations.AddIndex(
            model_name='bomitem',
            index=models.Index(fields=['j_and_n'], name='catalog_bom_j_and_n_f5f5b0_idx'),
        ),
        migrations.AddIndex(
            model_name='bomitem',
            index=models.Index(fields=['yt_number'], name='catalog_bom_yt_numb_9e7c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['manufacturer_number'], name='catalog_par_manufac_9a5447_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['item_no'], name='catalog_par_item_no_475b92_idx'),
        ),
        migrations.AddIndex(
            model_name='partinterchange',
            index=models.Index(fields=['interchange_number'], name='catalog_par_interch_9cf83a_idx'),
        ),
        migrations.AddIndex(
            model_name='partsuperseding',
            index=models.Index(fields=['old_part_number'], name='catalog_par_old_par_35a616_idx'),
        ),
        migrations.AddIndex(
            model_name='substitute',
            index=models.Index(fields=['substitute_number'], name='catalog_sub_substit_b2eb17_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['manufacturer'], name='catalog_uni_manufac_1f4cd8_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['j_and_n_number'], name='catalog_uni_j_and_n_e6dc1d_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['model_cat_number'], name='catalog_uni_model_c_82e614_idx'),
        ),
    ]
