# Generated by Django 6.0.1 on 2026-05-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_add_search_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearreductionsubstitution',
            name='supplier',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='gearreductionsubstitution',
            name='unit_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Unit Type'),
        ),
        migrations.AddField(
            model_name='substitute',
            name='substitute_supplier',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='substitute',
            name='substitute_unit_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Unit Type'),
        ),
        migrations.AlterField(
            model_name='crossreference',
            name='interchange_type',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Cross Ref Name'),
        ),
        migrations.AlterField(
            model_name='gearreductionsubstitution',
            name='number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Unit Number'),
        ),
    ]
