# Generated by Django 6.0.1 on 2026-05-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0043_add_substitute_and_gear_reduction_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearreductionsubstitution',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
