# Generated by Django 6.0.1 on 2026-05-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0044_gear_reduction_description_optional'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['unit_type_name'], name='catalog_app_unit_ty_89a112_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['is_active'], name='catalog_par_is_acti_ed1084_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['category'], name='catalog_par_categor_14110e_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['is_active'], name='catalog_uni_is_acti_da1cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['unit_type_category'], name='catalog_uni_unit_ty_5bd166_idx'),
        ),
    ]
