# Generated by Django 6.0.2 on 2026-05-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0045_add_list_page_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='price_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Price Updated'),
        ),
        migrations.AddField(
            model_name='unit',
            name='price_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Price Updated'),
        ),
    ]
