# Generated by Django 6.0.2 on 2026-05-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0046_price_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='price_updated_at',
        ),
        migrations.AddField(
            model_name='unit',
            name='new_price_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='New Price Updated'),
        ),
        migrations.AddField(
            model_name='unit',
            name='rebuilt_price_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rebuilt Price Updated'),
        ),
    ]
