# Generated by Django 6.0.2 on 2026-05-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_split_price_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossreference',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price'),
        ),
    ]
