# Generated by Django 6.0.2 on 2026-05-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0048_cross_reference_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='description',
            new_name='notes',
        ),
    ]
