# Generated by Django 6.0.2 on 2026-05-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0049_part_description_to_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Notes'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['is_active', 'name'], name='catalog_app_is_acti_2f06d1_idx'),
        ),
    ]
