# Generated by Django 6.0.2 on 2026-05-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0051_backfill_application_unit_numbers'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='partinterchange',
            constraint=models.UniqueConstraint(fields=('part', 'interchange_number', 'source_name'), name='unique_part_xref_number_source'),
        ),
    ]
