# Generated by Django 6.0.2 on 2026-06-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0053_add_covering_indexes_for_dropdowns'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='source_pdf',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Imported from PDF'),
        ),
        migrations.AddField(
            model_name='part',
            name='source_pdf',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Imported from PDF'),
        ),
        migrations.AddField(
            model_name='unit',
            name='source_pdf',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Imported from PDF'),
        ),
    ]
