# Generated by Django 6.0.1 on 2026-05-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_path', models.CharField(blank=True, default='', help_text='Full path to the backup destination (e.g. E:\\ApexBackups or D:\\Backups).', max_length=500, verbose_name='Backup Folder')),
                ('auto_backup_enabled', models.BooleanField(default=True, help_text='Automatically back up on app startup and periodically while running.', verbose_name='Auto-backup enabled')),
                ('backup_interval_hours', models.PositiveIntegerField(default=2, help_text='How often the app backs up while running (in addition to startup/shutdown).', verbose_name='Periodic backup interval (hours)')),
                ('max_backups', models.PositiveIntegerField(default=10, help_text='Oldest backups beyond this count are deleted automatically.', verbose_name='Max backups to keep')),
                ('last_backup_at', models.DateTimeField(blank=True, null=True, verbose_name='Last backup time')),
                ('last_backup_status', models.CharField(blank=True, default='', max_length=500, verbose_name='Last backup status')),
            ],
            options={
                'verbose_name': 'Backup Settings',
                'verbose_name_plural': 'Backup Settings',
            },
        ),
    ]
