# Generated by Django 6.0.1 on 2026-05-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0002_dual_paths_and_incremental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupsettings',
            name='max_backups',
            field=models.PositiveIntegerField(default=4, help_text='Number of historical database snapshots to keep. Oldest are deleted automatically.', verbose_name='Max DB snapshots to keep'),
        ),
    ]
