# Generated by Django 6.0.1 on 2026-05-11 11:54

from django.db import migrations


def update_max_backups(apps, schema_editor):
    BackupSettings = apps.get_model("backup", "BackupSettings")
    BackupSettings.objects.filter(max_backups=10).update(max_backups=4)


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0003_max_backups_default_4'),
    ]

    operations = [
        migrations.RunPython(update_max_backups, migrations.RunPython.noop),
    ]
