"""Round-two Application cleanup that finds duplicate patterns Phase A
(cleanup_normalize_applications) missed.

Runs four passes in a single transaction:

  Step 0  - Whitespace cleanup.  Collapses double-spaces to single spaces
            in `model` (~2,500 rows) and `engine` (~10 rows).  These are
            cosmetic parser artifacts (e.g. 'All Models  1986-1995').

  Step 1  - Make rename map.  Collapses 40+ formatting / spelling
            variants of the same brand to a single canonical spelling
            (e.g. 'GMC' -> 'Gmc', 'Mercedes Benz' -> 'Mercedes-Benz',
            'Bluebird' -> 'Blue Bird', 'Weidmann)' -> the canonical
            full brand name for parser-truncated values).  Pick of
            canonical follows the cross-ref cleanup precedent: the
            more-popular variant wins, with all-caps acronym proper
            nouns preserved where unambiguous.

  Step 2  - Model rename map.  Per-make, fixes the dominant
            'X- Y' -> 'X-Y' parser artifact (extra space after hyphen
            in models like 'F- 150', 'E- 350 Econoline') that came
            from PDF line-break splitting.  Auto-generated by scanning
            for (make, model) pairs where stripping the stray space
            produces an existing canonical model.

  Step 3  - Subset-pair merges (OPT-IN, default disabled).  For each
            configured (BASE_BRAND, VARIANT_BRAND) pair, finds rows
            under VARIANT_BRAND whose (model, engine, year) triple
            already exists under BASE_BRAND, re-points the ApplicationUnit
            links, then deletes the variant row.  Informational mode
            only by default -- prints candidate pairs and overlap counts
            so the user can opt-in pair-by-pair.

  Step 4  - Post-rename dedup.  After all renames, finds groups by
            (make, model, engine, year), keeps the lowest-id canonical,
            re-points every duplicate's ApplicationUnit M2M links to
            the canonical (collapsing collisions via update_or_create),
            and deletes the duplicates.

Usage::

    python manage.py cleanup_applications_v2              # dry-run (default)
    python manage.py cleanup_applications_v2 --dry-run    # explicit
    python manage.py cleanup_applications_v2 --commit     # apply
"""

from __future__ import annotations

import re
import time
from collections import defaultdict
from typing import Dict, List, Tuple

from django.core.management.base import BaseCommand, CommandError
from django.db import transaction

from catalog.models import Application, ApplicationUnit


# ---------------------------------------------------------------------------
# Make rename map.  Source -> canonical destination.
#
# Selection rule (matches cross-ref cleanup precedent):
#   * For acronym proper nouns, follow the row-population winner.
#   * For multi-word brands, follow the row-population winner unless one
#     spelling is clearly a parser artifact (trailing dash, broken paren).
# ---------------------------------------------------------------------------
MAKE_RENAME_MAP: Dict[str, str] = {
    # Casing / acronym variants -- popular variant wins
    "GMC": "Gmc",
    "BMW": "Bmw",
    "KHD": "Khd",
    "OMC": "Omc",
    "UD": "Ud",
    "MG": "Mg",
    "BPM": "Bpm",
    "Man": "MAN",
    "McCulloch": "Mcculloch",
    # Spelling / hyphenation / spacing -- popular variant wins
    "Case Ih": "Case/Ih",
    "Mercedes Benz": "Mercedes-Benz",
    "Harley Davidson": "Harley-Davidson",
    "Lister-Petter": "Lister Petter",
    "TCM Equipment": "Tcm Equipment",
    "Bluebird": "Blue Bird",
    "Ingersoll-Rand": "Ingersoll Rand",
    "Mitsubishi-Fuso": "Mitsubishi Fuso",
    "Agco Allis": "Agco-Allis",
    "MWM Diesel": "Mwm-Diesel",
    "Mwm Diesel": "Mwm-Diesel",
    "EZ-Go": "Ez-Go",
    "Red-D-Arc": "Red D Arc",
    "BMS Motorsports": "Bms Motorsports",
    "Bms Motor Sports": "Bms Motorsports",
    # Parser-truncation cases -- broken paren where only ONE canonical
    # full-brand candidate exists in the data.
    "Weidmann)": "Farymann (Farny & Weidmann)",
    "Division)": "White (Rio Division)",
    "Puch Ag)": "Steyr (Steyr-Daimler-Puch Ag)",
    "Holland)": "New Holland (Sperry New Holland)",
    # User-confirmed canonical pick for 'Group)' (455 rows) -- the
    # dominant in-data brand carrying the 'Deutz- Fahr Group' parens
    # is 'Same'; the other two candidates (Lamborghini, Dynapac) have
    # far fewer rows and a different parser-truncation source.
    "Group)": "Same (Deutz- Fahr Group)",
    # Trailing dash artifact -- 'Teledyne -' is a chopped 'Teledyne - X'
    "Teledyne -": "Teledyne",
}


# ---------------------------------------------------------------------------
# Subset-pair merges -- OPT-IN. Default empty.
#
# Format: (BASE_BRAND, VARIANT_BRAND).  Variant-brand rows whose
# (model, engine, year) triple already exists under BASE_BRAND have
# their ApplicationUnit links re-pointed to the base row and the
# variant Application row is deleted.
#
# Step 3 ALWAYS prints the overlap counts for candidate pairs so the
# user can decide what to enable.  See FINAL_SUBSET_CANDIDATES below
# for the candidate list this command will report on.
# ---------------------------------------------------------------------------
SUBSET_PAIRS: List[Tuple[str, str]] = [
    # User-confirmed Round-D enable list.  Each variant-brand row whose
    # (model, engine, year) triple already exists under the base brand
    # has its ApplicationUnit links re-pointed and the variant row
    # deleted.  Variants outside this list are reported on but skipped.
    ("Same", "Same (Deutz- Fahr Group)"),
    ("Aifo", "Aifo (Fiat)"),
    ("Mccormick", "Mccormick - Agricultural"),
    ("Bukh", "Bukh (Aabenraa)"),
    ("Farymann", "Farymann Diesel"),
]


# Subset-pair candidates to REPORT on in dry-run regardless of whether
# they're in SUBSET_PAIRS.  Pulled from the investigation scan.
FINAL_SUBSET_CANDIDATES: List[Tuple[str, str]] = [
    ("Volvo", "Volvo Penta"),
    ("Same", "Same (Deutz- Fahr Group)"),
    ("Aifo", "Aifo (Fiat)"),
    ("Mccormick", "Mccormick - Agricultural"),
    ("White", "White (Rio Division)"),
    ("Volvo", "Volvo (Bm)"),
    ("Deutz", "Deutz-Fahr"),
    ("White", "White (Mpls Moline)"),
    ("Bukh", "Bukh (Aabenraa)"),
    ("White", "White (Oliver)"),
    ("Farymann", "Farymann Diesel"),
    ("White", "White (Cockshutt)"),
    ("Mercruiser", "Mercruiser Stern Drive"),
    ("Teledyne", "Teledyne - Continental"),
    ("Lancia", "Lancia (Europe)"),
    ("Mercruiser", "Mercruiser Ski Engine"),
    ("Renault", "Renault Couach Marine"),
    ("Teledyne", "Teledyne - Wisconsin"),
]


# Pattern: hyphen followed by exactly one space inside a model string.
# Matches the dominant Ford / Jeep parser artifact ('F- 150', 'J- 2600').
HYPHEN_SPACE_RE = re.compile(r"- (?=\S)")

# Pattern: any double-or-more space.
DOUBLE_SPACE_RE = re.compile(r" {2,}")


class Command(BaseCommand):
    help = (
        "Round-two Application cleanup: whitespace fixes, make-name "
        "rename map, model-name rename map, subset-pair merges, and "
        "post-rename (make,model,engine,year) dedup with link re-pointing."
    )

    def add_arguments(self, parser):
        mode = parser.add_mutually_exclusive_group()
        mode.add_argument(
            "--dry-run",
            action="store_true",
            dest="dry_run",
            help="Report what would change without writing anything (default).",
        )
        mode.add_argument(
            "--commit",
            action="store_true",
            dest="commit",
            help="Apply changes inside a single transaction.",
        )

    # ================================================================== #
    # Main entry
    # ================================================================== #
    def handle(self, *args, **options):
        start = time.time()
        commit: bool = options["commit"]
        dry_run: bool = options["dry_run"]

        if not commit and not dry_run:
            dry_run = True
            self.stdout.write(self.style.WARNING(
                "No mode specified -- defaulting to --dry-run."
            ))
        mode_label = "COMMIT" if commit else "DRY-RUN"
        self.stdout.write(f"Mode: {mode_label}\n")
        self.stdout.flush()

        try:
            with transaction.atomic():
                before_apps = Application.objects.count()
                before_links = ApplicationUnit.objects.count()
                self.stdout.write(
                    f"Starting Application rows:     {before_apps:,}\n"
                    f"Starting ApplicationUnit links: {before_links:,}\n"
                )
                self.stdout.flush()

                step0 = self._step0_whitespace(commit)
                step1 = self._step1_make_renames(commit)
                step2 = self._step2_model_renames(commit)
                step3 = self._step3_subset_merges(commit)
                step4 = self._step4_post_rename_dedup(commit)

                if not commit:
                    transaction.set_rollback(True)

                after_apps = (
                    Application.objects.count()
                    if commit
                    else before_apps - (step3["deleted"] + step4["deleted"])
                )
                after_links = (
                    ApplicationUnit.objects.count()
                    if commit
                    else before_links  # link counts don't shrink (we
                                       # repoint, not delete)
                )

        except Exception as exc:
            raise CommandError(
                f"Aborting and rolling back: {exc.__class__.__name__}: {exc}"
            ) from exc

        # ============================================================== #
        # Summary
        # ============================================================== #
        self.stdout.write("\n" + "=" * 70)
        self.stdout.write("FINAL SUMMARY")
        self.stdout.write("=" * 70)
        self.stdout.write(
            f"Step 0 (whitespace + trailing period): "
            f"{step0['make_updated']:,} makes, "
            f"{step0['model_updated']:,} models, "
            f"{step0['engine_updated']:,} engines fixed"
        )
        self.stdout.write(
            f"Step 1 (make rename map):        "
            f"{step1['renamed']:,} renamed, "
            f"{step1['merged']:,} merged into Step-4 candidates"
        )
        self.stdout.write(
            f"Step 2 (model rename map):       "
            f"{step2['renamed']:,} renamed, "
            f"{step2['merged']:,} merged into Step-4 candidates"
        )
        self.stdout.write(
            f"Step 3 (subset-pair merges):     "
            f"{step3['deleted']:,} variant rows merged"
        )
        self.stdout.write(
            f"Step 4 (post-rename dedup):      "
            f"{step4['deleted']:,} rows deleted, "
            f"{step4['groups']:,} dup groups collapsed, "
            f"{step4['links_moved']:,} links re-pointed"
        )
        total_deleted = step3["deleted"] + step4["deleted"]
        self.stdout.write(f"\nTOTAL Application rows removed: {total_deleted:,}")
        self.stdout.write(
            f"Application: {before_apps:,} -> {after_apps:,} "
            f"({after_apps - before_apps:+,})"
        )
        self.stdout.write(
            f"ApplicationUnit links preserved: "
            f"{before_links:,} -> {after_links:,} "
            f"({after_links - before_links:+,})"
        )

        if not commit:
            self.stdout.write(self.style.WARNING(
                "\nDRY-RUN: no changes were made. "
                "Re-run with --commit to apply."
            ))
        else:
            self.stdout.write(self.style.SUCCESS(
                "\nCOMMIT: changes applied successfully."
            ))

        elapsed = time.time() - start
        self.stdout.write(f"\nElapsed: {elapsed:.2f}s")
        self.stdout.flush()

    # ================================================================== #
    # Step 0 - Whitespace cleanup (collapse double-spaces in model/engine)
    #          + trailing-period strip on make / model (Round-D add).
    # ================================================================== #
    def _step0_whitespace(self, commit: bool) -> dict:
        self.stdout.write("\n--- Step 0: Whitespace + trailing-period cleanup ---")
        self.stdout.flush()

        # Helper: combine double-space collapse + trailing-period strip
        # into a single canonicalizer per field.  Trailing periods on
        # make/model are pure parser artifacts (~1,279 rows, all
        # cosmetic) and never change the canonical brand identity.
        def normalize_value(raw: str, *, strip_trailing_period: bool) -> str:
            cleaned = DOUBLE_SPACE_RE.sub(" ", raw).strip()
            if strip_trailing_period:
                # Keep stripping only ONE trailing '.' (and any whitespace
                # uncovered by that strip).  Don't loop -- we want to
                # preserve legit '...' suffixes if any ever existed.
                if cleaned.endswith("."):
                    cleaned = cleaned[:-1].rstrip()
            return cleaned

        # --- Makes (trailing-period strip only; no double-space scan
        #     because make values are short single tokens / brand names) ---
        make_rows = list(
            Application.objects
            .filter(make__endswith=".")
            .values("id", "make")
        )
        make_updates: List[Tuple[int, str]] = []
        sample_makes: List[Tuple[str, str]] = []
        for r in make_rows:
            cleaned = normalize_value(r["make"], strip_trailing_period=True)
            if cleaned and cleaned != r["make"]:
                make_updates.append((r["id"], cleaned))
                if len(sample_makes) < 5:
                    sample_makes.append((r["make"], cleaned))

        # --- Models (double-space collapse + trailing-period strip) ---
        # Union of "has double-space" OR "ends with period".
        from django.db.models import Q
        model_rows = list(
            Application.objects
            .filter(Q(model__contains="  ") | Q(model__endswith="."))
            .values("id", "model")
        )
        model_updates: List[Tuple[int, str]] = []
        sample_models: List[Tuple[str, str]] = []
        for r in model_rows:
            cleaned = normalize_value(r["model"], strip_trailing_period=True)
            if cleaned and cleaned != r["model"]:
                model_updates.append((r["id"], cleaned))
                if len(sample_models) < 5:
                    sample_models.append((r["model"], cleaned))

        # --- Engines (double-space collapse only) ---
        engine_rows = list(
            Application.objects
            .filter(engine__contains="  ")
            .values("id", "engine")
        )
        engine_updates: List[Tuple[int, str]] = []
        sample_engines: List[Tuple[str, str]] = []
        for r in engine_rows:
            cleaned = normalize_value(r["engine"], strip_trailing_period=False)
            if cleaned and cleaned != r["engine"]:
                engine_updates.append((r["id"], cleaned))
                if len(sample_engines) < 5:
                    sample_engines.append((r["engine"], cleaned))

        self.stdout.write(
            f"  Makes with trailing period: {len(make_rows):,} -> "
            f"plan to fix {len(make_updates):,}"
        )
        self.stdout.write(
            f"  Models with double-space or trailing period: "
            f"{len(model_rows):,} -> plan to fix {len(model_updates):,}"
        )
        self.stdout.write(
            f"  Engines with double-space: {len(engine_rows):,} -> "
            f"plan to fix {len(engine_updates):,}"
        )
        if sample_makes:
            self.stdout.write("  Sample make fixes:")
            for before, after in sample_makes:
                self.stdout.write(f"    '{before}' -> '{after}'")
        if sample_models:
            self.stdout.write("  Sample model fixes:")
            for before, after in sample_models:
                self.stdout.write(f"    '{before}' -> '{after}'")
        if sample_engines:
            self.stdout.write("  Sample engine fixes:")
            for before, after in sample_engines:
                self.stdout.write(f"    '{before}' -> '{after}'")
        self.stdout.flush()

        if commit:
            self._bulk_update_field(make_updates, "make")
            self._bulk_update_field(model_updates, "model")
            self._bulk_update_field(engine_updates, "engine")

        return {
            "make_updated": len(make_updates),
            "model_updated": len(model_updates),
            "engine_updated": len(engine_updates),
        }

    # ================================================================== #
    # Step 1 - Make rename map
    # ================================================================== #
    def _step1_make_renames(self, commit: bool) -> dict:
        self.stdout.write("\n--- Step 1: Make rename map ---")
        self.stdout.flush()

        total_renamed = 0
        total_merged = 0

        for src, dst in MAKE_RENAME_MAP.items():
            n_src = Application.objects.filter(make=src).count()
            if n_src == 0:
                continue
            n_dst = Application.objects.filter(make=dst).count()

            self.stdout.write(
                f"  '{src}' ({n_src:,}) -> '{dst}' ({n_dst:,})"
            )
            self.stdout.flush()

            if commit:
                for i in range(0, n_src, 2000):
                    ids = list(
                        Application.objects.filter(make=src)
                        .order_by("id")
                        .values_list("id", flat=True)[i:i + 2000]
                    )
                    Application.objects.filter(id__in=ids).update(make=dst)
            total_renamed += n_src
            # Merging into Step 4 candidates is the dedup that will happen
            # automatically in Step 4 when post-rename rows collide.
            total_merged += min(n_src, n_dst)

        self.stdout.write(
            f"  Total: renamed {total_renamed:,}  "
            f"(potential Step-4 collisions ~{total_merged:,})"
        )

        self.stdout.flush()

        return {"renamed": total_renamed, "merged": total_merged}

    # ================================================================== #
    # Step 2 - Model rename map
    # ================================================================== #
    def _step2_model_renames(self, commit: bool) -> dict:
        self.stdout.write("\n--- Step 2: Model rename map (hyphen-space) ---")
        self.stdout.flush()

        # Scan: for every (make, raw_model) that contains '- <space><non-space>'
        # (the hyphen-space parser artifact), the canonical model is the
        # same string with the stray space removed.  We only rename when
        # the canonical exists OR when stripping creates a unique target.
        candidate_rows = list(
            Application.objects
            .filter(model__regex=r"- [^ ]")  # at least one '- X' pattern
            .values("id", "make", "model")
        )

        # Build a per-make rename plan
        per_make_buckets: Dict[Tuple[str, str], List[int]] = defaultdict(list)
        for r in candidate_rows:
            canonical = HYPHEN_SPACE_RE.sub("-", r["model"])
            if canonical == r["model"]:
                continue
            per_make_buckets[(r["make"], r["model"], canonical)].append(r["id"])

        # Renamed bucket dict has keys (make, raw_model, canonical) but we
        # need to also report on canonical-existence per make.
        # Convert to a list of (make, raw, canonical, ids).
        plan: List[Tuple[str, str, str, List[int]]] = []
        for key, ids in per_make_buckets.items():
            mk, raw, canonical = key
            plan.append((mk, raw, canonical, ids))
        plan.sort(key=lambda t: -len(t[3]))

        total_renamed = 0
        total_merged = 0
        sample_logged = 0
        for mk, raw, canonical, ids in plan:
            n_target = (
                Application.objects.filter(make=mk, model=canonical)
                .count()
            )
            if sample_logged < 10:
                self.stdout.write(
                    f"  make='{mk}' '{raw}' ({len(ids):,}) -> '{canonical}' "
                    f"(target has {n_target} existing rows)"
                )
                sample_logged += 1
            total_renamed += len(ids)
            total_merged += min(len(ids), n_target)
            if commit:
                for i in range(0, len(ids), 2000):
                    batch = ids[i:i + 2000]
                    Application.objects.filter(id__in=batch).update(
                        model=canonical
                    )

        remaining_unlogged = max(0, len(plan) - 10)
        if remaining_unlogged:
            self.stdout.write(
                f"  ... and {remaining_unlogged:,} more (make,model) "
                f"groups not shown"
            )
        self.stdout.write(
            f"  Total: renamed {total_renamed:,}  "
            f"(potential Step-4 collisions ~{total_merged:,})"
        )
        self.stdout.flush()

        return {"renamed": total_renamed, "merged": total_merged}

    # ================================================================== #
    # Step 3 - Subset-pair merges (informational by default)
    # ================================================================== #
    def _step3_subset_merges(self, commit: bool) -> dict:
        self.stdout.write("\n--- Step 3: Subset-pair merges ---")
        self.stdout.flush()

        # Always report on candidate pairs for user visibility
        self.stdout.write("  Candidate pairs (overlap on make+model+engine+year):")
        for base, variant in FINAL_SUBSET_CANDIDATES:
            base_keys = set(
                Application.objects.filter(make=base)
                .values_list("model", "engine", "year")
            )
            var_keys = set(
                Application.objects.filter(make=variant)
                .values_list("model", "engine", "year")
            )
            overlap = base_keys & var_keys
            enabled = (base, variant) in SUBSET_PAIRS
            flag = " [ENABLED]" if enabled else ""
            self.stdout.write(
                f"    '{base}' ({len(base_keys)} triples) vs "
                f"'{variant}' ({len(var_keys)} triples): "
                f"{len(overlap)} overlap{flag}"
            )
        self.stdout.flush()

        if not SUBSET_PAIRS:
            self.stdout.write("  No SUBSET_PAIRS enabled -- skipping merges.")
            return {"deleted": 0}

        # If enabled pairs exist, perform the merges.
        total_deleted = 0
        for base, variant in SUBSET_PAIRS:
            # Build the overlap set as (model, engine, year) triples
            base_triples = set(
                Application.objects.filter(make=base)
                .values_list("model", "engine", "year")
            )
            var_rows = list(
                Application.objects.filter(make=variant)
                .values("id", "model", "engine", "year")
            )
            to_merge: List[Tuple[int, int]] = []  # (variant_id, base_id)
            for r in var_rows:
                key = (r["model"], r["engine"], r["year"])
                if key not in base_triples:
                    continue
                # Find canonical (lowest-id) base row
                base_id = (
                    Application.objects.filter(
                        make=base,
                        model=r["model"],
                        engine=r["engine"],
                        year=r["year"],
                    )
                    .order_by("id")
                    .values_list("id", flat=True)
                    .first()
                )
                if base_id is None:
                    continue
                to_merge.append((r["id"], base_id))

            self.stdout.write(
                f"  '{variant}' -> merge {len(to_merge):,} rows into '{base}'"
            )
            self.stdout.flush()

            if commit and to_merge:
                self._merge_app_rows(to_merge)
            total_deleted += len(to_merge)

        self.stdout.write(
            f"  Total subset-pair rows merged: {total_deleted:,}"
        )
        return {"deleted": total_deleted}

    # ================================================================== #
    # Step 4 - Post-rename (make,model,engine,year) dedup
    # ================================================================== #
    def _step4_post_rename_dedup(self, commit: bool) -> dict:
        self.stdout.write("\n--- Step 4: Post-rename dedup ---")
        self.stdout.flush()

        # NOTE: in dry-run we haven't actually applied any renames, so
        # this step's row count is an UNDERESTIMATE.  We approximate the
        # post-rename state by building the dedup-key index ourselves
        # after applying renames in memory.

        # Build (post-rename make, model, engine, year) -> [ids]
        groups_map: Dict[Tuple[str, str, str, str], List[int]] = defaultdict(list)
        iterator = Application.objects.values_list(
            "id", "make", "model", "engine", "year"
        ).iterator(chunk_size=10000)
        for app_id, mk, md, en, yr in iterator:
            # Apply the in-memory rename transformations so dry-run can
            # see Step-0/Step-1/Step-2 collisions accurately.
            # Step-0 trailing-period strip on make (then Step-1 lookup).
            if mk.endswith("."):
                mk = mk[:-1].rstrip()
            mk_canon = MAKE_RENAME_MAP.get(mk, mk)
            # Step-2 hyphen-space + Step-0 double-space + trailing period
            # on model.
            if "- " in md:
                md_canon = HYPHEN_SPACE_RE.sub("-", md)
            else:
                md_canon = md
            md_canon = DOUBLE_SPACE_RE.sub(" ", md_canon).strip()
            if md_canon.endswith("."):
                md_canon = md_canon[:-1].rstrip()
            en_canon = DOUBLE_SPACE_RE.sub(" ", en).strip() if "  " in en else en
            groups_map[(mk_canon, md_canon, en_canon, yr)].append(app_id)

        # Find duplicate groups
        work_items: List[Tuple[int, List[int], Tuple[str, str, str, str]]] = []
        for key, ids in groups_map.items():
            if len(ids) <= 1:
                continue
            ids.sort()
            work_items.append((ids[0], ids[1:], key))

        n_groups = len(work_items)
        rows_deleted = sum(len(dups) for _, dups, _ in work_items)
        all_dup_ids = [aid for _, dups, _ in work_items for aid in dups]

        # Bulk-count the links pointing at any duplicate (chunked IN).
        links_repointed = 0
        for i in range(0, len(all_dup_ids), 5000):
            chunk = all_dup_ids[i:i + 5000]
            links_repointed += (
                ApplicationUnit.objects.filter(application_id__in=chunk)
                .count()
            )

        self.stdout.write(
            f"  Duplicate groups (post-rename make,model,engine,year): {n_groups:,}"
        )
        self.stdout.write(
            f"  Rows to delete:                                         {rows_deleted:,}"
        )
        self.stdout.write(
            f"  ApplicationUnit links to re-point:                      {links_repointed:,}"
        )

        # Sample
        sample = work_items[:5]
        if sample:
            self.stdout.write("  Sample dup groups:")
            for canonical, dups, key in sample:
                mk, md, en, yr = key
                lc = (
                    ApplicationUnit.objects.filter(application_id__in=dups)
                    .count()
                )
                self.stdout.write(
                    f"    canon=id={canonical}  "
                    f"key=({mk!r}, {md!r}, {en!r}, {yr!r})  "
                    f"dups={dups[:5]}{'...' if len(dups) > 5 else ''}  "
                    f"links_to_move={lc}"
                )
        self.stdout.flush()

        if commit:
            # Re-point each duplicate's links onto the canonical app,
            # collapsing (application, unit) collisions via update_or_create.
            for processed, (canonical_id, dup_ids, _) in enumerate(work_items, 1):
                for link in list(
                    ApplicationUnit.objects.filter(application_id__in=dup_ids)
                ):
                    defaults = {}
                    if link.position:
                        defaults["position"] = link.position
                    if link.notes:
                        defaults["notes"] = link.notes
                    ApplicationUnit.objects.update_or_create(
                        application_id=canonical_id,
                        unit_id=link.unit_id,
                        defaults=defaults,
                    )
                    link.delete()
                Application.objects.filter(id__in=dup_ids).delete()
                if processed % 5000 == 0:
                    self.stdout.write(
                        f"    committed {processed:,}/{n_groups:,} group(s)"
                    )
                    self.stdout.flush()

        return {
            "groups": n_groups,
            "deleted": rows_deleted,
            "links_moved": links_repointed,
        }

    # ================================================================== #
    # Helpers
    # ================================================================== #
    def _merge_app_rows(self, pairs: List[Tuple[int, int]]) -> None:
        """Re-point ApplicationUnit links from variant ids onto base ids,
        then delete the variant Application rows.

        `pairs` is a list of (variant_app_id, base_app_id).
        Uses update_or_create to handle (application, unit) collisions.
        """
        # Group by base for batch processing
        by_base: Dict[int, List[int]] = defaultdict(list)
        for var_id, base_id in pairs:
            by_base[base_id].append(var_id)

        for base_id, var_ids in by_base.items():
            for link in list(
                ApplicationUnit.objects.filter(application_id__in=var_ids)
            ):
                defaults = {}
                if link.position:
                    defaults["position"] = link.position
                if link.notes:
                    defaults["notes"] = link.notes
                ApplicationUnit.objects.update_or_create(
                    application_id=base_id,
                    unit_id=link.unit_id,
                    defaults=defaults,
                )
                link.delete()
            Application.objects.filter(id__in=var_ids).delete()

    def _bulk_update_field(
        self, pairs: List[Tuple[int, str]], field: str
    ) -> None:
        for i in range(0, len(pairs), 500):
            batch = pairs[i:i + 500]
            objs = list(
                Application.objects
                .filter(id__in=[p[0] for p in batch])
                .only("id", field)
            )
            value_map = dict(batch)
            for o in objs:
                setattr(o, field, value_map[o.id])
            Application.objects.bulk_update(objs, [field], batch_size=500)
