"""
Import data from LesterCD_Decrypted.db into Manchester Electric.
Supports --report-only (missing fields), --clear, --path, --verify.
"""
import sqlite3
import time
from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand
from django.db import connection, transaction

from catalog.models import (
    Application,
    ApplicationSpecification,
    ApplicationUnit,
    BOM,
    BOMItem,
    CrossReference,
    Part,
    Unit,
    UnitType,
)
from data_import.lester_schema import (
    APPLICATION_MAPPING,
    LESTER_UNMAPPED,
    PART_MAPPING,
    UNIT_MAPPING,
)


# Lester UnitTypeID -> Manchester Electric UnitType name
LESTER_UNIT_TYPE_MAP = {
    1: "Alternator",
    2: "Generator",
    3: "AC Motor",  # Lester MOTOR -> AC Motor
    4: "Starter",
}

BATCH_SIZE = 2000


class Command(BaseCommand):
    help = "Import Lester CD data into Manchester Electric. Use --report-only for missing fields."

    def add_arguments(self, parser):
        parser.add_argument(
            "--path",
            type=str,
            default=None,
            help="Path to LesterCD_Decrypted.db",
        )
        parser.add_argument(
            "--clear",
            action="store_true",
            help="Clear existing catalog data before import",
        )
        parser.add_argument(
            "--report-only",
            action="store_true",
            dest="report_only",
            help="Generate missing-fields report only, no import",
        )
        parser.add_argument(
            "--dry-run",
            action="store_true",
            dest="report_only",
            help="Alias for --report-only",
        )
        parser.add_argument(
            "--verify",
            action="store_true",
            help="Verify import: compare counts and sample data",
        )
        parser.add_argument(
            "--limit",
            type=int,
            default=None,
            help="Limit rows per table (for testing; e.g. --limit 1000)",
        )
        parser.add_argument(
            "--skip-to",
            type=str,
            default=None,
            dest="skip_to",
            help="Resume import from a step: units, parts, apps, boms, xrefs",
        )

    def handle(self, *args, **options):
        base_dir = Path(settings.BASE_DIR)
        path = options.get("path")
        db_path = Path(path) if path else base_dir / "LesterCD_Decrypted.db"

        if not db_path.exists():
            self.stdout.write(self.style.ERROR(f"Database not found: {db_path}"))
            return

        if options.get("report_only"):
            self._run_report_only(db_path, base_dir)
            return

        if options.get("verify"):
            self._run_verify(db_path, base_dir)
            return

        # Clear uses its own transaction; import uses batched commits
        if options.get("clear"):
            with transaction.atomic():
                self._clear_catalog_data()
        self._import_data(db_path, limit=options.get("limit"), skip_to=options.get("skip_to"))

    def _run_report_only(self, db_path: Path, base_dir: Path):
        """Generate missing-fields report for boss review."""
        report_path = base_dir / "docs" / "lester_missing_fields_report.txt"
        report_path.parent.mkdir(parents=True, exist_ok=True)

        lines = [
            "Lester CD -> Manchester Electric Missing Fields Report",
            "Generated by: import_lester --report-only",
            "Review this before running the full import.",
            "",
            "=" * 60,
            "",
        ]

        # Lester columns with no ME match
        lines.append("=== LESTER COLUMNS WITH NO MANCHESTER ELECTRIC MATCH ===")
        for table, cols in LESTER_UNMAPPED.items():
            if cols:
                lines.append(f"Table: {table}")
                for c in cols:
                    lines.append(f"  - {c}: (no ME field - data will be skipped or stored in notes)")
                lines.append("")

        # ME required fields
        lines.append("=== MANCHESTER ELECTRIC REQUIRED FIELDS WITH LESTER SOURCE ===")
        lines.append("Model: Unit")
        lines.append("  - unit_number: MAPPED from AltGenStrDetails.PIC#")
        lines.append("Model: Part")
        lines.append("  - part_number: MAPPED from ComponentPartDetails.PIC#")
        lines.append("Model: Application")
        lines.append("  - name: BUILT from Make + Model + Submodel + Engine + Year (Lester Applications + lookups)")
        lines.append("")

        # Suggested mappings
        lines.append("=== SUGGESTED MAPPINGS (confirmed for import) ===")
        lines.append("")
        lines.append("AltGenStrDetails (Units):")
        for lester, me in UNIT_MAPPING.items():
            if me:
                lines.append(f"  {lester} -> Unit.{me}")
        lines.append("")
        lines.append("Applications:")
        for lester, me in APPLICATION_MAPPING.items():
            if me and lester not in ("MakeID", "ModelID", "SubModelID"):
                lines.append(f"  {lester} -> Application.{me}")
        lines.append("  MakeID+ModelID+SubModelID -> Application.name (via tblMasterMake, tblMasterModel, tblMasterSubmodel)")
        lines.append("")
        lines.append("ComponentPartDetails (Parts):")
        for lester, me in PART_MAPPING.items():
            if me:
                lines.append(f"  {lester} -> Part.{me}")
        lines.append("")
        lines.append("BillOfMaterials:")
        lines.append("  UnitPIC# -> BOM.unit (Unit), ComponentPIC# -> BOMItem.part (Part)")
        lines.append("")
        lines.append("Interchanges:")
        lines.append("  PIC# -> unit, InterchangeNumber -> cross_ref_unit (when both are Units)")
        lines.append("")

        report_path.write_text("\n".join(lines), encoding="utf-8")
        self.stdout.write(self.style.SUCCESS(f"Report written to {report_path}"))

    def _run_verify(self, db_path: Path, base_dir: Path):
        """Compare Lester counts vs Manchester Electric counts."""
        report_path = base_dir / "docs" / "lester_import_verification.txt"
        report_path.parent.mkdir(parents=True, exist_ok=True)

        conn = sqlite3.connect(str(db_path))
        cursor = conn.cursor()

        # Lester counts
        lester_counts = {}
        # Only compare main data tables (not lookup tables)
        compare_tables = ("AltGenStrDetails", "Applications", "ComponentPartDetails", "BillOfMaterials", "Interchanges")
        for t in compare_tables:
            cursor.execute(f'SELECT COUNT(*) FROM "{t}"')
            lester_counts[t] = cursor.fetchone()[0]

        # ME counts (approximate mapping) - catch db lock
        try:
            me_counts = {
                "AltGenStrDetails": Unit.objects.count(),
                "Applications": Application.objects.count(),
                "ComponentPartDetails": Part.objects.count(),
                "BillOfMaterials": BOMItem.objects.count(),
                "Interchanges": CrossReference.objects.count(),
            }
        except Exception:
            me_counts = {t: "Error (db locked?)" for t in lester_counts}
            self.stdout.write(
                self.style.WARNING("ME database locked or error - report shows Lester counts only.")
            )

        lines = [
            "Lester CD Import Verification Report",
            "Source vs Manchester Electric",
            "",
            "=" * 60,
            "",
            "=== COUNT COMPARISON ===",
            "",
        ]
        for table, lester_n in lester_counts.items():
            me_n = me_counts.get(table, "N/A")
            if isinstance(me_n, int):
                diff = lester_n - me_n
                status = "OK" if diff == 0 else f"DIFF: {diff}"
                lines.append(f"{table}: Lester={lester_n}, ME={me_n} [{status}]")
            else:
                lines.append(f"{table}: Lester={lester_n}, ME={me_n}")
        lines.append("")

        # Sample spot-check (only if ME db accessible)
        lines.append("=== SAMPLE SPOT-CHECK (first 3 Units) ===")
        cursor.execute('SELECT "PIC#" FROM "AltGenStrDetails" LIMIT 3')
        sample_pics = [r[0] for r in cursor.fetchall()]
        try:
            for pic in sample_pics:
                unit = Unit.objects.filter(unit_number=pic).first()
                if unit:
                    lines.append(f"  Lester PIC# {pic} -> ME Unit {unit.unit_number} (OK)")
                else:
                    lines.append(f"  Lester PIC# {pic} -> NOT FOUND in ME")
        except Exception:
            for pic in sample_pics:
                lines.append(f"  Lester PIC# {pic} -> (ME db not accessible for check)")
        lines.append("")

        conn.close()
        report_path.write_text("\n".join(lines), encoding="utf-8")
        self.stdout.write(self.style.SUCCESS(f"Verification written to {report_path}"))

    def _clear_catalog_data(self):
        """Clear catalog data (preserve UnitType, CompanySettings).

        Uses raw SQL to avoid SQLite's SQLITE_MAX_VARIABLE_NUMBER limit
        when Django tries to cascade-delete large tables via ORM.
        """
        tables = [
            BOMItem._meta.db_table,
            BOM._meta.db_table,
            CrossReference._meta.db_table,
            ApplicationUnit._meta.db_table,
            ApplicationSpecification._meta.db_table,
            Part._meta.db_table,
            Unit._meta.db_table,
            Application._meta.db_table,
        ]
        with connection.cursor() as cur:
            for table in tables:
                cur.execute(f'DELETE FROM "{table}"')
                self.stdout.write(f"  Cleared {table}")
        self.stdout.write("Cleared catalog data.")

    def _import_data(self, db_path: Path, limit: int = None, skip_to: str = None):
        """Import from Lester DB using batched commits and bulk_create."""
        steps = ["units", "parts", "apps", "boms", "xrefs"]
        start_idx = 0
        if skip_to:
            if skip_to not in steps:
                self.stdout.write(self.style.ERROR(f"Invalid --skip-to: {skip_to}. Use: {steps}"))
                return
            start_idx = steps.index(skip_to)
            self.stdout.write(f"Resuming from step: {skip_to}")

        t0 = time.time()
        conn = sqlite3.connect(str(db_path), timeout=60)
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()

        # Load lookups into memory
        cursor.execute("SELECT Id, UnitType FROM tblMasterUnitType")
        unit_type_map = {r["Id"]: r["UnitType"] for r in cursor.fetchall()}
        cursor.execute("SELECT Id, Manufacturer FROM tblMasterManufacturer")
        manufacturer_map = {r["Id"]: r["Manufacturer"] for r in cursor.fetchall()}
        cursor.execute("SELECT Id, MakeName FROM tblMasterMake")
        make_map = {r["Id"]: r["MakeName"] for r in cursor.fetchall()}
        cursor.execute("SELECT Id, MakeID, ModelName FROM tblMasterModel")
        model_map = {r["Id"]: (r["MakeID"], r["ModelName"]) for r in cursor.fetchall()}
        cursor.execute("SELECT Id, ModelId, SubmodelName FROM tblMasterSubmodel")
        submodel_map = {r["Id"]: (r["ModelId"], r["SubmodelName"]) for r in cursor.fetchall()}
        cursor.execute("SELECT Id, PartType FROM tblMasterPartType")
        part_type_map = {r["Id"]: r["PartType"] for r in cursor.fetchall()}
        cursor.execute("SELECT Id, StarterType FROM tblMasterStarterType")
        starter_type_map = {r["Id"]: r["StarterType"] for r in cursor.fetchall()}
        cursor.execute("SELECT Id, InterchangeType FROM tblMasterInterchangeType")
        interchange_type_map = {r["Id"]: r["InterchangeType"] for r in cursor.fetchall()}
        self.stdout.write(f"Loaded lookups in {time.time()-t0:.1f}s")

        # Ensure UnitTypes exist
        me_unit_types = {}
        for lester_id, lester_name in unit_type_map.items():
            me_name = LESTER_UNIT_TYPE_MAP.get(lester_id, lester_name)
            if me_name == "MOTOR":
                me_name = "AC Motor"
            ut, _ = UnitType.objects.get_or_create(name=me_name, defaults={"description": lester_name})
            me_unit_types[lester_id] = ut

        # Always load PIC->pk maps (needed for BOM/xref even when skipping)
        unit_pic_to_id = {}
        part_pic_to_id = {}
        if start_idx > 0:
            for u in Unit.objects.values_list("pk", "unit_number"):
                unit_pic_to_id[u[1]] = u[0]
            for p in Part.objects.values_list("pk", "part_number"):
                part_pic_to_id[p[1]] = p[0]
            self.stdout.write(f"Loaded {len(unit_pic_to_id)} units, {len(part_pic_to_id)} parts from DB.")

        def _sql(table):
            s = f'SELECT * FROM "{table}"'
            if limit:
                s += f" LIMIT {limit}"
            return s

        # ---- Step 0: Units ----
        if start_idx <= 0:
            cursor.execute(_sql("AltGenStrDetails"))
            rows = cursor.fetchall()
            batch = []
            for row in rows:
                pic = row["PIC#"]
                if not pic:
                    continue
                ut_id = row["UnitTypeID"]
                ut = me_unit_types.get(ut_id) if ut_id else None
                oem = manufacturer_map.get(row["ManufacturerID"], "") if row["ManufacturerID"] else ""
                notes_parts = []
                if row["ShortNote"]:
                    notes_parts.append(str(row["ShortNote"])[:500])
                notes = "\n".join(notes_parts)[:2000] if notes_parts else ""
                st_id = row["StarterTypeID"]
                starter_type_name = starter_type_map.get(st_id, "") if st_id else ""
                batch.append(Unit(
                    unit_number=pic,
                    voltage=row["Voltage"] or "",
                    rotation=row["Rotation"] or "",
                    amp_rating=row["Amperage"] or "",
                    power_rating=row["PowerSize"] or "",
                    kw_hp=row["PowerUnits"] or "",
                    tooth_quantity=row["Teeth"] or "",
                    regulator_type=row["Regulator"] or "",
                    unit_type=ut,
                    oem=oem[:200],
                    clock_position=(row["ClockPosition"] or "")[:50],
                    pulley_class=(row["PulleyClass"] or "")[:100],
                    starter_type=starter_type_name[:100],
                    unit_attributes=row["LongNote"] or "",
                    notes=notes[:2000],
                ))
                if len(batch) >= BATCH_SIZE:
                    Unit.objects.bulk_create(batch, ignore_conflicts=True)
                    batch = []
            if batch:
                Unit.objects.bulk_create(batch, ignore_conflicts=True)
            for u in Unit.objects.values_list("pk", "unit_number"):
                unit_pic_to_id[u[1]] = u[0]
            self.stdout.write(f"Imported {len(unit_pic_to_id)} units in {time.time()-t0:.1f}s")

        # ---- Step 1: Parts ----
        if start_idx <= 1:
            t1 = time.time()
            cursor.execute(_sql("ComponentPartDetails"))
            rows = cursor.fetchall()
            batch = []
            for row in rows:
                pic = row["PIC#"]
                if not pic:
                    continue
                pt = part_type_map.get(row["PartTypeID"], "") if row["PartTypeID"] else ""
                oem = manufacturer_map.get(row["ManufacturerID"], "") if row["ManufacturerID"] else ""
                desc = row["Dimensions"] or ""
                if row["ShortNote"]:
                    desc = f"{desc}\n{row['ShortNote']}".strip()[:2000]
                batch.append(Part(
                    part_number=pic,
                    part_name=row["PartClass"] or pic,
                    type=pt[:100],
                    category=row["PartClass"] or "",
                    oem=oem[:200],
                    description=desc[:2000],
                    foot_notes=row["LongNote"] or "",
                ))
                if len(batch) >= BATCH_SIZE:
                    Part.objects.bulk_create(batch, ignore_conflicts=True)
                    batch = []
            if batch:
                Part.objects.bulk_create(batch, ignore_conflicts=True)
            for p in Part.objects.values_list("pk", "part_number"):
                part_pic_to_id[p[1]] = p[0]
            self.stdout.write(f"Imported {len(part_pic_to_id)} parts in {time.time()-t1:.1f}s")

        # ---- Step 2: Applications + ApplicationUnit ----
        if start_idx <= 2:
            t2 = time.time()
            cursor.execute(_sql("Applications"))
            rows = cursor.fetchall()
            app_batch = []
            app_unit_pics = []  # parallel list: PIC# for each app in batch
            app_unit_lesters = []  # parallel list: Lester# for position
            app_count = 0
            au_count = 0
            total = len(rows)
            for i, row in enumerate(rows):
                make_name = make_map.get(row["MakeID"], "") if row["MakeID"] else ""
                model_row = model_map.get(row["ModelID"]) if row["ModelID"] else None
                model_name = model_row[1] if model_row else ""
                sub_row = submodel_map.get(row["SubModelID"]) if row["SubModelID"] else None
                sub_name = sub_row[1] if sub_row else ""
                name_parts = [p for p in [make_name, model_name, sub_name, row["Engine"], row["YearRange"]] if p]
                name = " ".join(str(p) for p in name_parts)[:200] or f"App-{row['ID']}"
                if not name.strip():
                    name = f"Application-{row['ID']}"
                name = f"{name} [#{row['ID']}]"[:255]
                mfr = manufacturer_map.get(row["ManufacturerID"], "") if row["ManufacturerID"] else ""
                app_ut_id = row["UnitTypeID"]
                app_ut_name = ""
                if app_ut_id:
                    lester_ut = unit_type_map.get(app_ut_id, "")
                    app_ut_name = LESTER_UNIT_TYPE_MAP.get(app_ut_id, lester_ut)
                app_batch.append(Application(
                    name=name[:255],
                    make=make_name[:150],
                    engine=(row["Engine"] or "")[:150],
                    year=(row["YearRange"] or "")[:50],
                    mfr=mfr[:150],
                    fuel_type=(row["FuelType"] or "")[:50],
                    vin=(row["VIN"] or "")[:50],
                    alt_pulley=(row["AltPulley"] or "")[:100],
                    unit_type_name=app_ut_name[:100],
                    part_number=(row["Lester#"] or "")[:100],
                    unit_number=(row["PIC#"] or "")[:100],
                    other_number=(row["PrimaryOE"] or "")[:100],
                    options=(row["Options"] or "")[:500],
                    notes=(row["Comment"] or "")[:500],
                ))
                app_unit_pics.append(row["PIC#"] or "")
                app_unit_lesters.append(row["Lester#"] or "")

                if len(app_batch) >= BATCH_SIZE:
                    created = Application.objects.bulk_create(app_batch)
                    app_count += len(created)
                    au_batch = []
                    for app_obj, pic, lester in zip(created, app_unit_pics, app_unit_lesters):
                        if pic and pic in unit_pic_to_id:
                            au_batch.append(ApplicationUnit(
                                application=app_obj,
                                unit_id=unit_pic_to_id[pic],
                                position=lester,
                            ))
                    if au_batch:
                        ApplicationUnit.objects.bulk_create(au_batch, ignore_conflicts=True)
                        au_count += len(au_batch)
                    app_batch = []
                    app_unit_pics = []
                    app_unit_lesters = []

                if (i + 1) % 10000 == 0:
                    self.stdout.write(f"  Applications: {i+1}/{total}...")

            if app_batch:
                created = Application.objects.bulk_create(app_batch)
                app_count += len(created)
                au_batch = []
                for app_obj, pic, lester in zip(created, app_unit_pics, app_unit_lesters):
                    if pic and pic in unit_pic_to_id:
                        au_batch.append(ApplicationUnit(
                            application=app_obj,
                            unit_id=unit_pic_to_id[pic],
                            position=lester,
                        ))
                if au_batch:
                    ApplicationUnit.objects.bulk_create(au_batch, ignore_conflicts=True)
                    au_count += len(au_batch)
            self.stdout.write(f"Imported {app_count} applications, {au_count} app-unit links in {time.time()-t2:.1f}s")

        # ---- Step 3: BOMs ----
        if start_idx <= 3:
            t3 = time.time()
            cursor.execute(_sql("BillOfMaterials"))
            rows = cursor.fetchall()
            bom_map = {}
            bom_item_batch = []
            seen_bom_items = set()
            skipped = 0
            for row in rows:
                unit_pic = row["UnitPIC#"]
                comp_pic = row["ComponentPIC#"]
                if unit_pic not in unit_pic_to_id or comp_pic not in part_pic_to_id:
                    skipped += 1
                    continue
                if unit_pic not in bom_map:
                    bom = BOM.objects.create(
                        name=f"BOM-{unit_pic}",
                        unit_id=unit_pic_to_id[unit_pic],
                    )
                    bom_map[unit_pic] = bom.pk
                pair = (bom_map[unit_pic], part_pic_to_id[comp_pic])
                if pair not in seen_bom_items:
                    seen_bom_items.add(pair)
                    bom_item_batch.append(BOMItem(
                        bom_id=bom_map[unit_pic],
                        part_id=part_pic_to_id[comp_pic],
                        unit_qty=1,
                    ))
                if len(bom_item_batch) >= BATCH_SIZE:
                    BOMItem.objects.bulk_create(bom_item_batch, ignore_conflicts=True)
                    bom_item_batch = []
            if bom_item_batch:
                BOMItem.objects.bulk_create(bom_item_batch, ignore_conflicts=True)
            self.stdout.write(
                f"Imported {len(bom_map)} BOMs, {len(seen_bom_items)} BOM items "
                f"(skipped {skipped}) in {time.time()-t3:.1f}s"
            )

        # ---- Step 4: CrossReferences (all interchanges) ----
        if start_idx <= 4:
            t4 = time.time()
            cursor.execute(_sql("Interchanges"))
            rows = cursor.fetchall()
            xref_batch = []
            seen_xrefs = set()
            unit_linked = 0
            mfr_linked = 0
            skipped = 0
            total = len(rows)
            for i, row in enumerate(rows):
                pic = row["PIC#"]
                other = row["InterchangeNumber"]
                if not pic or not other or pic not in unit_pic_to_id:
                    skipped += 1
                    continue
                it_id = row["InterchangeTypeID"]
                it_name = ""
                if it_id:
                    try:
                        it_name = interchange_type_map.get(int(it_id), "")
                    except (ValueError, TypeError):
                        it_name = str(it_id)
                dedup_key = (unit_pic_to_id[pic], other, it_name)
                if dedup_key in seen_xrefs:
                    continue
                seen_xrefs.add(dedup_key)
                other_unit_id = unit_pic_to_id.get(other)
                if other_unit_id and other != pic:
                    xref_batch.append(CrossReference(
                        unit_id=unit_pic_to_id[pic],
                        cross_ref_unit_id=other_unit_id,
                        cross_ref_number=other[:100],
                        interchange_type=it_name[:150],
                    ))
                    unit_linked += 1
                else:
                    xref_batch.append(CrossReference(
                        unit_id=unit_pic_to_id[pic],
                        cross_ref_number=other[:100],
                        interchange_type=it_name[:150],
                    ))
                    mfr_linked += 1
                if len(xref_batch) >= BATCH_SIZE:
                    CrossReference.objects.bulk_create(xref_batch, ignore_conflicts=True)
                    xref_batch = []
                if (i + 1) % 100000 == 0:
                    self.stdout.write(f"  Interchanges: {i+1}/{total}...")
            if xref_batch:
                CrossReference.objects.bulk_create(xref_batch, ignore_conflicts=True)
            self.stdout.write(
                f"Imported {unit_linked + mfr_linked} cross references "
                f"({unit_linked} unit-linked, {mfr_linked} manufacturer) "
                f"skipped {skipped} in {time.time()-t4:.1f}s"
            )

        conn.close()
        elapsed = time.time() - t0
        self.stdout.write(self.style.SUCCESS(f"Import complete in {elapsed:.0f}s."))
