"""
Inspect LesterCD_Decrypted.db schema: tables, columns, row counts, sample rows.
Writes report to docs/lester_schema_report.txt.
"""
from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand


class Command(BaseCommand):
    help = "Inspect LesterCD database schema and write report to docs/lester_schema_report.txt"

    def add_arguments(self, parser):
        parser.add_argument(
            "--path",
            type=str,
            default=None,
            help="Path to LesterCD_Decrypted.db (default: project root)",
        )

    def handle(self, *args, **options):
        base_dir = Path(settings.BASE_DIR)
        path = options.get("path")
        if path:
            db_path = Path(path)
        else:
            db_path = base_dir / "LesterCD_Decrypted.db"

        if not db_path.exists():
            self.stdout.write(
                self.style.ERROR(f"Database not found: {db_path}")
            )
            self.stdout.write(
                "Place LesterCD_Decrypted.db in the project root or pass --path"
            )
            return

        report_path = base_dir / "docs" / "lester_schema_report.txt"
        report_path.parent.mkdir(parents=True, exist_ok=True)

        import sqlite3
        conn = sqlite3.connect(str(db_path))
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()

        cursor.execute(
            "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"
        )
        tables = [r[0] for r in cursor.fetchall()]

        lines = [
            f"Lester CD Database Schema Report",
            f"Source: {db_path}",
            f"Generated by inspect_lester_db",
            "",
            "=" * 60,
            "",
        ]

        for table in tables:
            cursor.execute(f'PRAGMA table_info("{table}")')
            cols = cursor.fetchall()
            col_info = ", ".join(f"{c[1]} ({c[2]})" for c in cols)
            cursor.execute(f'SELECT COUNT(*) FROM "{table}"')
            count = cursor.fetchone()[0]
            cursor.execute(f'SELECT * FROM "{table}" LIMIT 1')
            sample = cursor.fetchone()
            if sample:
                sample_str = str(dict(zip(sample.keys(), sample)))
            else:
                sample_str = "(no rows)"
            if len(sample_str) > 200:
                sample_str = sample_str[:200] + "..."

            lines.extend([
                f"=== TABLE: {table} ===",
                f"  Columns: {col_info}",
                f"  Row count: {count}",
                f"  Sample: {sample_str}",
                "",
            ])

        conn.close()

        report_path.write_text("\n".join(lines), encoding="utf-8")
        self.stdout.write(self.style.SUCCESS(f"Report written to {report_path}"))
